version: 2

models:
  - name: fact_pageviews
    description: "Table with events for page_views. Unique per order_id."
    columns:
      - name: event_id
        tests:
          - not_null
          - unique 
      - name: user_id
        tests:
          - not_null
      - name: page_url
        tests:
          - not_null
  - name: fact_session_order
    description: "Table with information about sessions."
    columns:
      - name: user_id
        tests:
          - not_null
      - name: session_id
        tests:  
          - not_null
          - unique
     
